name: Deploy Fitple

on:
  push:
    branches: [ policyadd ]  # ← 니가 사용하는 브랜치명에 따라 수정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build Fitple
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Get current time
        uses: josStorer/get-current-time@v2.0.2
        id: current-time
        with:
          format: YYYY-MM-DD_HHmmss  # 언더바로 돼 있어야 함
          utcOffset: "+09:00"

      - name: Set artifact
        run: echo "artifact=$(basename $(ls ./build/libs/*.jar | grep -v plain))" >> $GITHUB_ENV

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: springboot-developer            # 기존 앱 이름 그대로!
          environment_name: springboot-developer-env        # 환경도 그대로!
          version_label: fitple-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: build/libs/${{ env.artifact }}
